name: Deploy infrastructure changes

on:
  push:
    branches:
      - main
    paths:
      - clockify/terraform/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Deploy
      env:
        TF_VAR_postgres_username: ${{ secrets.TF_VAR_POSTGRES_USERNAME }}
        TF_VAR_postgres_password: ${{ secrets.TF_VAR_POSTGRES_PASSWORD }}
      run: |
        cd clockify
        cd terraform
        terraform init
        terraform apply -auto-approve 
